# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='has_availability',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='host_acceptance_rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='neighbourhood_group_cleansed',
            field=models.CharField(default='a', max_length=1),
            preserve_default=False,
        ),
    ]
