# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0002_auto_20171028_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='jurisdiction_names',
            field=models.CharField(default='a', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='license',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
    ]
