# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0003_auto_20171028_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='count',
        ),
        migrations.AlterField(
            model_name='listing',
            name='host_picture_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='host_thumbnail_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='host_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='medium_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='thumbnail_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='xl_picture_url',
            field=models.CharField(max_length=300),
        ),
    ]
