# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0005_auto_20171028_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='experiences_offered',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='neighborhood_overview',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='space',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='summary',
            field=models.CharField(max_length=10000),
        ),
    ]
