# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0012_auto_20171028_0327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
