# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0015_auto_20171028_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
