# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0017_auto_20171028_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='notes',
            field=models.CharField(max_length=10000),
        ),
    ]
