# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0019_auto_20171028_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='access',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='experiences_offered',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='house_rules',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='interaction',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='neighborhood_overview',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='transit',
            field=models.CharField(max_length=10000),
        ),
    ]
