# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0031_auto_20171028_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='neighbourhood',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='neighbourhood_cleansed',
            field=models.CharField(max_length=2000),
        ),
    ]
